version: '3'

services:
  web:
    image: webserver:latest 
    ports:
      - "80:80"
    volumes:
      - ./:/usr/local/apache2/htdocs/
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    restart: always