version: '3'

services:
  web:
    build: 
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "80:80"
    restart: always
    volumes:
      - webserver:/usr/local/apache2/
volumes:
  webserver:
