version: '3'

services:
  web:
    image: httpd:latest 
    ports:
      - "80:80"
    volumes:
      - ./:/usr/local/apache2/htdocs/
      - ./conf/my-httpd.conf:/usr/local/apache2/conf/my-httpd.conf
    restart: always