version: '3'

services:
  web:
    image: webserver:latest 
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs/
      - ./conf:/usr/local/apache2/conf/

    restart: always